# Generated by Django 3.0.5 on 2020-05-04 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajo', models.CharField(max_length=50, verbose_name='Trabajo')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(choices=[('V', 'Varon'), ('M', 'Mujer'), ('O', 'Otro')], default='', max_length=1, verbose_name='Sexo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.Trabajo'),
        ),
    ]
